name: Build Develop Image

on:
  push:
    branches:
      - dev
    tags:
      - "dev-[0-9]+.[0-9]+.[0-9]+"

jobs:
  run-es-lint:
    name: Run ES Lint
    uses: ./.github/workflows/reusable/run-es-lint.yaml

  build-and-push-to-registry:
    name: Run Auto Tests
    uses: ./.github/workflows/reusable/build-and-push-to-registry.yaml
    with:
      tags: |
        type=raw,value=${{ github.ref_name }}
        type=raw,value=dev-latest