name: Build Production Image

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

jobs:
  run-es-lint:
    name: Run ES Lint
    uses: ./.github/reusable/run-es-lint.yaml

  run-auto-test:
    name: Run Auto Tests
    uses: ./.github/reusable/run-auto-test.yaml

  build-and-push-to-registry:
    name: Run Auto Tests
    uses: ./.github/reusable/run-auto-test.yaml
    with:
      tags: |
        type=raw,value=${{ github.ref_name }}
        type=raw,value=latest