name: Build Develop Image

on:
  push:
    tags:
      - "dev-[0-9]+.[0-9]+.[0-9]+"

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  run-es-lint:
    name: Run ES Lint
    uses: ./.github/workflows/run-es-lint.yaml

  build-and-push-to-registry:
    name: Build
    needs:
      - run-es-lint
    uses: ./.github/workflows/build-and-push-to-registry.yaml
    with:
      tags: |
        type=raw,value=${{ github.ref_name }}
        type=raw,value=dev-latest