name: Build Production Image

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

jobs:
  run-es-lint:
    name: Run ES Lint
    uses: ./.github/workflows/run-es-lint.yaml

  run-auto-test:
    name: Run Auto Tests
    uses: ./.github/workflows/run-auto-test.yaml

  build-and-push-to-registry:
    name: Build
    needs:
      - run-es-lint
      - run-auto-test
    uses: ./.github/workflows/build-and-push-to-registry.yaml
    with:
      tags: |
        type=raw,value=${{ github.ref_name }}
        type=raw,value=latest

  deploy:
    name: Deploy
    needs:
      - build-and-push-to-registry
    uses: ./.github/workflows/deploy.yaml
    with:
      tag: ${{ github.ref_name }}