name: auto-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-es-lint:
    name: Run ES Lint
    uses: ./.github/reusable/run-es-lint.yaml

  run-auto-test:
    name: Run Auto Tests
    uses: ./.github/reusable/run-auto-test.yaml